version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "homefirstoperation"
    AWS_DEFAULT_REGION: "ap-south-1"
    ACCOUNT_ID: "155372231032"
    DOCKER_USERNAME: "harshithffc"
    DOCKER_PASSWORD: "Aezakmi@123"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies and setting up JDK..."
      -

  pre_build:
    commands:
      - echo "Login to Amazon ECR..."
      - |
        for dir in $(ls $SERVICES_DIR); do
          if [ -f "$SERVICES_DIR/$dir/Dockerfile" ]; then
            REPO="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$dir"
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO
          fi
        done
      - echo "Login to DockerHub..."
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Detecting changed services..."
      - |
        git diff --name-only HEAD~1 HEAD | cut -d/ -f1 | sort | uniq > changed-services.txt
      - echo "Changed services:"
      - cat changed-services.txt

  build:
    commands:
      - echo "Building only changed microservices..."
      - |
        while read service; do
          if [ -f "$SERVICES_DIR/$service/Dockerfile" ]; then
            echo "Building $service"
            cd $SERVICES_DIR/$service
            ./gradlew clean build --no-daemon || true
            REPO="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$service"
            docker build -t $REPO:latest .
            docker tag $REPO:latest $REPO:$IMAGE_TAG
            cd ../..
          fi
        done < changed-services.txt

  post_build:
    commands:
      - echo "Pushing changed Docker images to ECR..."
      - |
        echo "[" > imagedefinitions.json
        first=true
        while read service; do
          if [ -f "$SERVICES_DIR/$service/Dockerfile" ]; then
            REPO="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$service"
            docker push $REPO:latest
            docker push $REPO:$IMAGE_TAG

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> imagedefinitions.json
            fi

            echo "{\"name\":\"$service\",\"imageUri\":\"$REPO:$IMAGE_TAG\"}" >> imagedefinitions.json
          fi
        done < changed-services.txt
        echo "]" >> imagedefinitions.json
      - echo "Final imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
