version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "homefirstoperation"
    AWS_DEFAULT_REGION: "ap-south-1"
    ACCOUNT_ID: "155372231032"
    DOCKER_USERNAME: "harshithffc"
    DOCKER_PASSWORD: "Aezakmi@123"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies and setting up JDK..."
      -

  pre_build:
    commands:
      - echo "Checking if there are any changes in the $SERVICE_NAME service..."
      - |
        CHANGED=$(git diff --name-only HEAD~1 HEAD | grep "^$SERVICE_NAME/")
        if [ -z "$CHANGED" ]; then
          echo "No changes in $SERVICE_NAME. Skipping build and push."
          exit 0
        fi
      - echo "Changes detected in $SERVICE_NAME, proceeding with build."
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building $SERVICE_NAME..."
      - cd $SERVICE_NAME
      - chmod +x gradlew
      - ./gradlew clean build --no-daemon
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - cd ..

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
